Metrics/LineLength:
  Exclude:
    - spec/*

Metrics/MethodLength:
  Max: 9

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Style/TrivialAccessors:
  AllowPredicates: true

Style/TrailingComma:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  MaxSlashes: 0

